//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSFE.Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_local() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSFE.Language.en_local", typeof(en_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open register.
        /// </summary>
        internal static string acept_open_register {
            get {
                return ResourceManager.GetString("acept_open_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add payment.
        /// </summary>
        internal static string add_payment {
            get {
                return ResourceManager.GetString("add_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A = Requires authorization.
        /// </summary>
        internal static string admin_caption_description {
            get {
                return ResourceManager.GetString("admin_caption_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin pin.
        /// </summary>
        internal static string admin_pin {
            get {
                return ResourceManager.GetString("admin_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount paid.
        /// </summary>
        internal static string amount_paid {
            get {
                return ResourceManager.GetString("amount_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article.
        /// </summary>
        internal static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article return.
        /// </summary>
        internal static string article_return {
            get {
                return ResourceManager.GetString("article_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles.
        /// </summary>
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attendance.
        /// </summary>
        internal static string attendance {
            get {
                return ResourceManager.GetString("attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bar code.
        /// </summary>
        internal static string bar_code {
            get {
                return ResourceManager.GetString("bar_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel invoice.
        /// </summary>
        internal static string cancel_invoice {
            get {
                return ResourceManager.GetString("cancel_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash desk closing.
        /// </summary>
        internal static string cash_desk_closing {
            get {
                return ResourceManager.GetString("cash_desk_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash fund.
        /// </summary>
        internal static string cash_fund {
            get {
                return ResourceManager.GetString("cash_fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash in hand.
        /// </summary>
        internal static string cash_in_hand {
            get {
                return ResourceManager.GetString("cash_in_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cashier.
        /// </summary>
        internal static string cashier {
            get {
                return ResourceManager.GetString("cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C = Authorized Cashiers.
        /// </summary>
        internal static string cashier_caption_description {
            get {
                return ResourceManager.GetString("cashier_caption_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cashiers.
        /// </summary>
        internal static string cashiers {
            get {
                return ResourceManager.GetString("cashiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar caja.
        /// </summary>
        internal static string close_register {
            get {
                return ResourceManager.GetString("close_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error when trying to close register.
        /// </summary>
        internal static string close_register_error {
            get {
                return ResourceManager.GetString("close_register_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register closed successfully .
        /// </summary>
        internal static string close_register_success {
            get {
                return ResourceManager.GetString("close_register_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to close the register?.
        /// </summary>
        internal static string close_register_warning {
            get {
                return ResourceManager.GetString("close_register_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash register setup.
        /// </summary>
        internal static string config_register {
            get {
                return ResourceManager.GetString("config_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cost.
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coupon.
        /// </summary>
        internal static string coupon {
            get {
                return ResourceManager.GetString("coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply coupon.
        /// </summary>
        internal static string coupon_apply {
            get {
                return ResourceManager.GetString("coupon_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit note.
        /// </summary>
        internal static string credit_note {
            get {
                return ResourceManager.GetString("credit_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit note add Successfully .
        /// </summary>
        internal static string credit_note_success {
            get {
                return ResourceManager.GetString("credit_note_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string customer_email {
            get {
                return ResourceManager.GetString("customer_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identification.
        /// </summary>
        internal static string customer_identification {
            get {
                return ResourceManager.GetString("customer_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identification type.
        /// </summary>
        internal static string customer_identification_type {
            get {
                return ResourceManager.GetString("customer_identification_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer name.
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string customer_phone {
            get {
                return ResourceManager.GetString("customer_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed at.
        /// </summary>
        internal static string date_close_register {
            get {
                return ResourceManager.GetString("date_close_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opened at.
        /// </summary>
        internal static string date_open_register {
            get {
                return ResourceManager.GetString("date_open_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete item.
        /// </summary>
        internal static string delete_Items {
            get {
                return ResourceManager.GetString("delete_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposit.
        /// </summary>
        internal static string deposit {
            get {
                return ResourceManager.GetString("deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposits.
        /// </summary>
        internal static string deposits {
            get {
                return ResourceManager.GetString("deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposit description.
        /// </summary>
        internal static string description_deposit_amount {
            get {
                return ResourceManager.GetString("description_deposit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Withdrawal description.
        /// </summary>
        internal static string description_withdrawal_amount {
            get {
                return ResourceManager.GetString("description_withdrawal_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply discount.
        /// </summary>
        internal static string dicount_apply {
            get {
                return ResourceManager.GetString("dicount_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Discount.
        /// </summary>
        internal static string discount_general {
            get {
                return ResourceManager.GetString("discount_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Discount.
        /// </summary>
        internal static string discount_line {
            get {
                return ResourceManager.GetString("discount_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount per amount.
        /// </summary>
        internal static string discount_per_amount {
            get {
                return ResourceManager.GetString("discount_per_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount per percent.
        /// </summary>
        internal static string discount_per_percent {
            get {
                return ResourceManager.GetString("discount_per_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discounts.
        /// </summary>
        internal static string discounts {
            get {
                return ResourceManager.GetString("discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter admin code.
        /// </summary>
        internal static string enter_admin_code {
            get {
                return ResourceManager.GetString("enter_admin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error invalid pin.
        /// </summary>
        internal static string error_admin_pin {
            get {
                return ResourceManager.GetString("error_admin_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string error_exist_partial_nc {
            get {
                return ResourceManager.GetString("error_exist_partial_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, there is a missing payment.
        /// </summary>
        internal static string error_missing_payment {
            get {
                return ResourceManager.GetString("error_missing_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error numeric.
        /// </summary>
        internal static string error_numeric {
            get {
                return ResourceManager.GetString("error_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error opening the cash register, you must enter a valid amount..
        /// </summary>
        internal static string error_open_cash {
            get {
                return ResourceManager.GetString("error_open_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t pay zero amount.
        /// </summary>
        internal static string error_paid_zero {
            get {
                return ResourceManager.GetString("error_paid_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error trying to save changes..
        /// </summary>
        internal static string error_save_message {
            get {
                return ResourceManager.GetString("error_save_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error trying to save invoice.
        /// </summary>
        internal static string error_saving_invoice {
            get {
                return ResourceManager.GetString("error_saving_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find weigh item.
        /// </summary>
        internal static string find_and_weigh_item {
            get {
                return ResourceManager.GetString("find_and_weigh_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free.
        /// </summary>
        internal static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group permission.
        /// </summary>
        internal static string group_permission {
            get {
                return ResourceManager.GetString("group_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a H = Hidde module.
        /// </summary>
        internal static string hidde_caption_description {
            get {
                return ResourceManager.GetString("hidde_caption_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register number.
        /// </summary>
        internal static string id_register {
            get {
                return ResourceManager.GetString("id_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User id.
        /// </summary>
        internal static string id_user {
            get {
                return ResourceManager.GetString("id_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identification is required.
        /// </summary>
        internal static string identification_required {
            get {
                return ResourceManager.GetString("identification_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice items.
        /// </summary>
        internal static string invoice_items {
            get {
                return ResourceManager.GetString("invoice_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice key.
        /// </summary>
        internal static string invoice_key {
            get {
                return ResourceManager.GetString("invoice_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice number.
        /// </summary>
        internal static string invoice_number {
            get {
                return ResourceManager.GetString("invoice_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items Invoice.
        /// </summary>
        internal static string itemsinvoice {
            get {
                return ResourceManager.GetString("itemsinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items to credit note.
        /// </summary>
        internal static string Itemstonc {
            get {
                return ResourceManager.GetString("Itemstonc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail is required.
        /// </summary>
        internal static string mail_required {
            get {
                return ResourceManager.GetString("mail_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize.
        /// </summary>
        internal static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be decimal.
        /// </summary>
        internal static string must_decimal {
            get {
                return ResourceManager.GetString("must_decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be integer.
        /// </summary>
        internal static string must_integer {
            get {
                return ResourceManager.GetString("must_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must select an item.
        /// </summary>
        internal static string must_select_an_item {
            get {
                return ResourceManager.GetString("must_select_an_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar el tipo de identificacion..
        /// </summary>
        internal static string must_select_identify_type {
            get {
                return ResourceManager.GetString("must_select_identify_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be string.
        /// </summary>
        internal static string must_string {
            get {
                return ResourceManager.GetString("must_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name is required.
        /// </summary>
        internal static string name_required {
            get {
                return ResourceManager.GetString("name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not enough products.
        /// </summary>
        internal static string not_enough_products {
            get {
                return ResourceManager.GetString("not_enough_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open cash register.
        /// </summary>
        internal static string open_register {
            get {
                return ResourceManager.GetString("open_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator panel.
        /// </summary>
        internal static string panel_admin {
            get {
                return ResourceManager.GetString("panel_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay.
        /// </summary>
        internal static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay cash.
        /// </summary>
        internal static string pay_cash {
            get {
                return ResourceManager.GetString("pay_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay with card.
        /// </summary>
        internal static string pay_with_card {
            get {
                return ResourceManager.GetString("pay_with_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment method.
        /// </summary>
        internal static string payment_method {
            get {
                return ResourceManager.GetString("payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payments.
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission to open register.
        /// </summary>
        internal static string permission_to_open_cash {
            get {
                return ResourceManager.GetString("permission_to_open_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string phone_format {
            get {
                return ResourceManager.GetString("phone_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone is required.
        /// </summary>
        internal static string phone_required {
            get {
                return ResourceManager.GetString("phone_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proces credit note.
        /// </summary>
        internal static string process_nc {
            get {
                return ResourceManager.GetString("process_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promotion.
        /// </summary>
        internal static string promotion {
            get {
                return ResourceManager.GetString("promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promotions.
        /// </summary>
        internal static string promotions {
            get {
                return ResourceManager.GetString("promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string qty_nc {
            get {
                return ResourceManager.GetString("qty_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string qty_sold {
            get {
                return ResourceManager.GetString("qty_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The amount cannot be less than or equal to 0.
        /// </summary>
        internal static string quantity_error {
            get {
                return ResourceManager.GetString("quantity_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the type of credit note.
        /// </summary>
        internal static string questions_nc_type {
            get {
                return ResourceManager.GetString("questions_nc_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reprint register.
        /// </summary>
        internal static string reprint_register {
            get {
                return ResourceManager.GetString("reprint_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Review product.
        /// </summary>
        internal static string review_product {
            get {
                return ResourceManager.GetString("review_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save deposit.
        /// </summary>
        internal static string save_deposit {
            get {
                return ResourceManager.GetString("save_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save withdrawal.
        /// </summary>
        internal static string save_withdrawal {
            get {
                return ResourceManager.GetString("save_withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search product.
        /// </summary>
        internal static string search_product {
            get {
                return ResourceManager.GetString("search_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standby.
        /// </summary>
        internal static string standby {
            get {
                return ResourceManager.GetString("standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string sub_total_amount {
            get {
                return ResourceManager.GetString("sub_total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved successfully.
        /// </summary>
        internal static string success_save_message {
            get {
                return ResourceManager.GetString("success_save_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax.
        /// </summary>
        internal static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax amount.
        /// </summary>
        internal static string tax_amount {
            get {
                return ResourceManager.GetString("tax_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax rate.
        /// </summary>
        internal static string tax_rate {
            get {
                return ResourceManager.GetString("tax_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taxes.
        /// </summary>
        internal static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total bank.
        /// </summary>
        internal static string total_bank {
            get {
                return ResourceManager.GetString("total_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total cash.
        /// </summary>
        internal static string total_cash {
            get {
                return ResourceManager.GetString("total_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total cash in close.
        /// </summary>
        internal static string total_cash_in_close {
            get {
                return ResourceManager.GetString("total_cash_in_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Cash Sales.
        /// </summary>
        internal static string total_cash_sales {
            get {
                return ResourceManager.GetString("total_cash_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total change.
        /// </summary>
        internal static string total_change {
            get {
                return ResourceManager.GetString("total_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total deposit in close.
        /// </summary>
        internal static string total_deposit_in_close {
            get {
                return ResourceManager.GetString("total_deposit_in_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difference in cash.
        /// </summary>
        internal static string total_diff_cash {
            get {
                return ResourceManager.GetString("total_diff_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difference in bank.
        /// </summary>
        internal static string total_diff_deposit {
            get {
                return ResourceManager.GetString("total_diff_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total discount.
        /// </summary>
        internal static string total_discount_amount {
            get {
                return ResourceManager.GetString("total_discount_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total invoice.
        /// </summary>
        internal static string total_invoice_amount {
            get {
                return ResourceManager.GetString("total_invoice_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items.
        /// </summary>
        internal static string total_item_count {
            get {
                return ResourceManager.GetString("total_item_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total items.
        /// </summary>
        internal static string total_items_amount {
            get {
                return ResourceManager.GetString("total_items_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lines.
        /// </summary>
        internal static string total_line_invoice {
            get {
                return ResourceManager.GetString("total_line_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total paid.
        /// </summary>
        internal static string total_paid {
            get {
                return ResourceManager.GetString("total_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total sale.
        /// </summary>
        internal static string total_sale {
            get {
                return ResourceManager.GetString("total_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Services.
        /// </summary>
        internal static string total_services_amount {
            get {
                return ResourceManager.GetString("total_services_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total tax.
        /// </summary>
        internal static string total_tax_amount {
            get {
                return ResourceManager.GetString("total_tax_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User login error.
        /// </summary>
        internal static string user_login_error {
            get {
                return ResourceManager.GetString("user_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to open the cash register with amount 0?.
        /// </summary>
        internal static string warning_open_zero {
            get {
                return ResourceManager.GetString("warning_open_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Withdrawal.
        /// </summary>
        internal static string withdrawal {
            get {
                return ResourceManager.GetString("withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Withdrawals.
        /// </summary>
        internal static string withdrawals {
            get {
                return ResourceManager.GetString("withdrawals", resourceCulture);
            }
        }
    }
}
