//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSFE.Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_local() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSFE.Language.es_local", typeof(es_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir caja.
        /// </summary>
        internal static string acept_open_register {
            get {
                return ResourceManager.GetString("acept_open_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar pago.
        /// </summary>
        internal static string add_payment {
            get {
                return ResourceManager.GetString("add_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A = Requiere autorizacion.
        /// </summary>
        internal static string admin_caption_description {
            get {
                return ResourceManager.GetString("admin_caption_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin del administrador.
        /// </summary>
        internal static string admin_pin {
            get {
                return ResourceManager.GetString("admin_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto pagado.
        /// </summary>
        internal static string amount_paid {
            get {
                return ResourceManager.GetString("amount_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articulo.
        /// </summary>
        internal static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolución de articulo.
        /// </summary>
        internal static string article_return {
            get {
                return ResourceManager.GetString("article_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articulos.
        /// </summary>
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencia.
        /// </summary>
        internal static string attendance {
            get {
                return ResourceManager.GetString("attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de barra.
        /// </summary>
        internal static string bar_code {
            get {
                return ResourceManager.GetString("bar_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular factura.
        /// </summary>
        internal static string cancel_invoice {
            get {
                return ResourceManager.GetString("cancel_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre de caja.
        /// </summary>
        internal static string cash_desk_closing {
            get {
                return ResourceManager.GetString("cash_desk_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fondo de caja.
        /// </summary>
        internal static string cash_fund {
            get {
                return ResourceManager.GetString("cash_fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectivo de apertura.
        /// </summary>
        internal static string cash_in_hand {
            get {
                return ResourceManager.GetString("cash_in_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cajero.
        /// </summary>
        internal static string cashier {
            get {
                return ResourceManager.GetString("cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C = Autorizado para cajeros.
        /// </summary>
        internal static string cashier_caption_description {
            get {
                return ResourceManager.GetString("cashier_caption_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cajeros.
        /// </summary>
        internal static string cashiers {
            get {
                return ResourceManager.GetString("cashiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar caja.
        /// </summary>
        internal static string close_register {
            get {
                return ResourceManager.GetString("close_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar de cerrar la caja.
        /// </summary>
        internal static string close_register_error {
            get {
                return ResourceManager.GetString("close_register_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La caja se ha cerrado correctamente .
        /// </summary>
        internal static string close_register_success {
            get {
                return ResourceManager.GetString("close_register_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea cerrar la caja?.
        /// </summary>
        internal static string close_register_warning {
            get {
                return ResourceManager.GetString("close_register_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion caja registradora.
        /// </summary>
        internal static string config_register {
            get {
                return ResourceManager.GetString("config_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo.
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cupon.
        /// </summary>
        internal static string coupon {
            get {
                return ResourceManager.GetString("coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Cupon.
        /// </summary>
        internal static string coupon_apply {
            get {
                return ResourceManager.GetString("coupon_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota de crédito.
        /// </summary>
        internal static string credit_note {
            get {
                return ResourceManager.GetString("credit_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota de credito aplicada correctamente.
        /// </summary>
        internal static string credit_note_success {
            get {
                return ResourceManager.GetString("credit_note_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electronico.
        /// </summary>
        internal static string customer_email {
            get {
                return ResourceManager.GetString("customer_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificacion.
        /// </summary>
        internal static string customer_identification {
            get {
                return ResourceManager.GetString("customer_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de identificacion.
        /// </summary>
        internal static string customer_identification_type {
            get {
                return ResourceManager.GetString("customer_identification_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string customer_phone {
            get {
                return ResourceManager.GetString("customer_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha cierre.
        /// </summary>
        internal static string date_close_register {
            get {
                return ResourceManager.GetString("date_close_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha apertura.
        /// </summary>
        internal static string date_open_register {
            get {
                return ResourceManager.GetString("date_open_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar articulo.
        /// </summary>
        internal static string delete_Items {
            get {
                return ResourceManager.GetString("delete_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposito.
        /// </summary>
        internal static string deposit {
            get {
                return ResourceManager.GetString("deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depositos.
        /// </summary>
        internal static string deposits {
            get {
                return ResourceManager.GetString("deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion del deposito .
        /// </summary>
        internal static string description_deposit_amount {
            get {
                return ResourceManager.GetString("description_deposit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion del retiro.
        /// </summary>
        internal static string description_withdrawal_amount {
            get {
                return ResourceManager.GetString("description_withdrawal_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar descuento.
        /// </summary>
        internal static string dicount_apply {
            get {
                return ResourceManager.GetString("dicount_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento general.
        /// </summary>
        internal static string discount_general {
            get {
                return ResourceManager.GetString("discount_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento de linea.
        /// </summary>
        internal static string discount_line {
            get {
                return ResourceManager.GetString("discount_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento por monto.
        /// </summary>
        internal static string discount_per_amount {
            get {
                return ResourceManager.GetString("discount_per_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento por porcentaje.
        /// </summary>
        internal static string discount_per_percent {
            get {
                return ResourceManager.GetString("discount_per_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuentos.
        /// </summary>
        internal static string discounts {
            get {
                return ResourceManager.GetString("discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el codigo de administrador.
        /// </summary>
        internal static string enter_admin_code {
            get {
                return ResourceManager.GetString("enter_admin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar de agregar el cliente.
        /// </summary>
        internal static string error_add_customer {
            get {
                return ResourceManager.GetString("error_add_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al ingresar el pin.
        /// </summary>
        internal static string error_admin_pin {
            get {
                return ResourceManager.GetString("error_admin_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede anular una factura con nota de credito parcial aplicada, esto puede afectar el cierre y la contabilidad..
        /// </summary>
        internal static string error_exist_partial_nc {
            get {
                return ResourceManager.GetString("error_exist_partial_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, existe un faltante de pago.
        /// </summary>
        internal static string error_missing_payment {
            get {
                return ResourceManager.GetString("error_missing_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error numerico.
        /// </summary>
        internal static string error_numeric {
            get {
                return ResourceManager.GetString("error_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al abrir la caja registradora, debe ingresar un monto valido..
        /// </summary>
        internal static string error_open_cash {
            get {
                return ResourceManager.GetString("error_open_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede pagar monto cero.
        /// </summary>
        internal static string error_paid_zero {
            get {
                return ResourceManager.GetString("error_paid_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar de cuardar los cambios..
        /// </summary>
        internal static string error_save_message {
            get {
                return ResourceManager.GetString("error_save_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar la factura.
        /// </summary>
        internal static string error_saving_invoice {
            get {
                return ResourceManager.GetString("error_saving_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar articulo a pesar.
        /// </summary>
        internal static string find_and_weigh_item {
            get {
                return ResourceManager.GetString("find_and_weigh_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gratis.
        /// </summary>
        internal static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero de permisos.
        /// </summary>
        internal static string group_permission {
            get {
                return ResourceManager.GetString("group_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a H = Ocultar modulo.
        /// </summary>
        internal static string hidde_caption_description {
            get {
                return ResourceManager.GetString("hidde_caption_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de caja.
        /// </summary>
        internal static string id_register {
            get {
                return ResourceManager.GetString("id_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Usuario.
        /// </summary>
        internal static string id_user {
            get {
                return ResourceManager.GetString("id_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificacion requerida.
        /// </summary>
        internal static string identification_required {
            get {
                return ResourceManager.GetString("identification_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items de la factura.
        /// </summary>
        internal static string invoice_items {
            get {
                return ResourceManager.GetString("invoice_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string invoice_key {
            get {
                return ResourceManager.GetString("invoice_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de factura.
        /// </summary>
        internal static string invoice_number {
            get {
                return ResourceManager.GetString("invoice_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items de la factura.
        /// </summary>
        internal static string itemsinvoice {
            get {
                return ResourceManager.GetString("itemsinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items de la Nota de Credito.
        /// </summary>
        internal static string Itemstonc {
            get {
                return ResourceManager.GetString("Itemstonc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesion.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electronico requerido.
        /// </summary>
        internal static string mail_required {
            get {
                return ResourceManager.GetString("mail_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimizar.
        /// </summary>
        internal static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser decimal.
        /// </summary>
        internal static string must_decimal {
            get {
                return ResourceManager.GetString("must_decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser numero entero.
        /// </summary>
        internal static string must_integer {
            get {
                return ResourceManager.GetString("must_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un articulo.
        /// </summary>
        internal static string must_select_an_item {
            get {
                return ResourceManager.GetString("must_select_an_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar el tipo de identificacion..
        /// </summary>
        internal static string must_select_identify_type {
            get {
                return ResourceManager.GetString("must_select_identify_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser texto.
        /// </summary>
        internal static string must_string {
            get {
                return ResourceManager.GetString("must_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre requerido.
        /// </summary>
        internal static string name_required {
            get {
                return ResourceManager.GetString("name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay productos suficientes.
        /// </summary>
        internal static string not_enough_products {
            get {
                return ResourceManager.GetString("not_enough_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura de caja.
        /// </summary>
        internal static string open_register {
            get {
                return ResourceManager.GetString("open_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel administrador.
        /// </summary>
        internal static string panel_admin {
            get {
                return ResourceManager.GetString("panel_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago en efectivo.
        /// </summary>
        internal static string pay_cash {
            get {
                return ResourceManager.GetString("pay_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago con tarjeta.
        /// </summary>
        internal static string pay_with_card {
            get {
                return ResourceManager.GetString("pay_with_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metodo de pago.
        /// </summary>
        internal static string payment_method {
            get {
                return ResourceManager.GetString("payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permiso de administrador para abrir caja.
        /// </summary>
        internal static string permission_to_open_cash {
            get {
                return ResourceManager.GetString("permission_to_open_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en numero telefonico.
        /// </summary>
        internal static string phone_format {
            get {
                return ResourceManager.GetString("phone_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono requerido.
        /// </summary>
        internal static string phone_required {
            get {
                return ResourceManager.GetString("phone_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar nota de credito.
        /// </summary>
        internal static string process_nc {
            get {
                return ResourceManager.GetString("process_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promocion.
        /// </summary>
        internal static string promotion {
            get {
                return ResourceManager.GetString("promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promociones.
        /// </summary>
        internal static string promotions {
            get {
                return ResourceManager.GetString("promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad devuelta.
        /// </summary>
        internal static string qty_nc {
            get {
                return ResourceManager.GetString("qty_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad vendida.
        /// </summary>
        internal static string qty_sold {
            get {
                return ResourceManager.GetString("qty_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad no puede ser menor ni igual al 0..
        /// </summary>
        internal static string quantity_error {
            get {
                return ResourceManager.GetString("quantity_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el tipo de nota de crédito.
        /// </summary>
        internal static string questions_nc_type {
            get {
                return ResourceManager.GetString("questions_nc_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reimprimir cierre.
        /// </summary>
        internal static string reprint_register {
            get {
                return ResourceManager.GetString("reprint_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta producto.
        /// </summary>
        internal static string review_product {
            get {
                return ResourceManager.GetString("review_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar deposito.
        /// </summary>
        internal static string save_deposit {
            get {
                return ResourceManager.GetString("save_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar retiro.
        /// </summary>
        internal static string save_withdrawal {
            get {
                return ResourceManager.GetString("save_withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar producto.
        /// </summary>
        internal static string search_product {
            get {
                return ResourceManager.GetString("search_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya vuelvo.
        /// </summary>
        internal static string standby {
            get {
                return ResourceManager.GetString("standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string sub_total_amount {
            get {
                return ResourceManager.GetString("sub_total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exito.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado correctamente..
        /// </summary>
        internal static string success_save_message {
            get {
                return ResourceManager.GetString("success_save_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impuesto.
        /// </summary>
        internal static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto de impuesto.
        /// </summary>
        internal static string tax_amount {
            get {
                return ResourceManager.GetString("tax_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa de impuesto.
        /// </summary>
        internal static string tax_rate {
            get {
                return ResourceManager.GetString("tax_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impuestos.
        /// </summary>
        internal static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total en tarjeta.
        /// </summary>
        internal static string total_bank {
            get {
                return ResourceManager.GetString("total_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total en efectivo.
        /// </summary>
        internal static string total_cash {
            get {
                return ResourceManager.GetString("total_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total en efectivo reportado.
        /// </summary>
        internal static string total_cash_in_close {
            get {
                return ResourceManager.GetString("total_cash_in_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total ventas en efectivo.
        /// </summary>
        internal static string total_cash_sales {
            get {
                return ResourceManager.GetString("total_cash_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vuelto.
        /// </summary>
        internal static string total_change {
            get {
                return ResourceManager.GetString("total_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total en tarjeta reportado.
        /// </summary>
        internal static string total_deposit_in_close {
            get {
                return ResourceManager.GetString("total_deposit_in_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diferencia en efectivo.
        /// </summary>
        internal static string total_diff_cash {
            get {
                return ResourceManager.GetString("total_diff_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diferencia en tarjeta.
        /// </summary>
        internal static string total_diff_deposit {
            get {
                return ResourceManager.GetString("total_diff_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de descuento.
        /// </summary>
        internal static string total_discount_amount {
            get {
                return ResourceManager.GetString("total_discount_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total  factura.
        /// </summary>
        internal static string total_invoice_amount {
            get {
                return ResourceManager.GetString("total_invoice_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items.
        /// </summary>
        internal static string total_item_count {
            get {
                return ResourceManager.GetString("total_item_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Mercancia.
        /// </summary>
        internal static string total_items_amount {
            get {
                return ResourceManager.GetString("total_items_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lineas.
        /// </summary>
        internal static string total_line_invoice {
            get {
                return ResourceManager.GetString("total_line_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total pagado.
        /// </summary>
        internal static string total_paid {
            get {
                return ResourceManager.GetString("total_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Venta.
        /// </summary>
        internal static string total_sale {
            get {
                return ResourceManager.GetString("total_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Servicios.
        /// </summary>
        internal static string total_services_amount {
            get {
                return ResourceManager.GetString("total_services_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Impuesto.
        /// </summary>
        internal static string total_tax_amount {
            get {
                return ResourceManager.GetString("total_tax_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar sesion de usuario.
        /// </summary>
        internal static string user_login_error {
            get {
                return ResourceManager.GetString("user_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea abrir la caja registradora en 0?.
        /// </summary>
        internal static string warning_open_zero {
            get {
                return ResourceManager.GetString("warning_open_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retiro.
        /// </summary>
        internal static string withdrawal {
            get {
                return ResourceManager.GetString("withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retiros.
        /// </summary>
        internal static string withdrawals {
            get {
                return ResourceManager.GetString("withdrawals", resourceCulture);
            }
        }
    }
}
